# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('created',), 'permissions': (('persona', 'Permite al usuario gestionar persona'),)},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='cargo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='duplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[(b'S', b'Soltero/a'), (b'D', b'Divorciado/a'), (b'C', b'Casado/a'), (b'U', b'Union Libre'), (b'', b'---------')], max_length=1),
        ),
        migrations.AddField(
            model_name='persona',
            name='fax',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='fotografia',
            field=models.ImageField(blank=True, help_text=b'El archivo debe estar en formato jpg o png y no pesar mas de 120kb', null=True, upload_to=b'persona/foto//%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='persona',
            name='mostrar_en_cardex',
            field=models.BooleanField(default=False, verbose_name=b'Es representante legal'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='profesion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='rtn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], max_length=1),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[(b'R', b'Carnet de Residencia'), (b'L', b'Licencia'), (b'P', b'Pasaporte'), (b'T', b'Tarjeta de Identidad'), (b'N', b'Ninguno')], max_length=1),
        ),
    ]
