# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20171025_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
